- name: Install docker and docker-compose
  pip:
    name: 
       - docker
       - docker-compose

- name: clone-repo
  git:
    dest: "{{ deplyment_path }}"
    repo: "{{ git_repository }}"
    version: "{{ git_branch }}"


- name: run docker-compose
  docker-compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes 
